spring.application.name=spring-security-4.0
server.servlet.context-path=/abs
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/loan_db
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform

# JWT config
jwt.secretKey=pZxk8vN2q4dF3tR0sV7yJ9wQh2ZfD3LmT8Kb1uY5xCr0ePq9sXn4mVt6rAq2Hj8P
jwt.accessTokenExpirationMinutes=15
jwt.refreshTokenExpirationDays=30
